---
abstract: 'mock Apache environment for testing and debugging'
author:
  - 'Andrew Ford <andrew@ford-mason.co.uk>'
build_requires:
  ExtUtils::MakeMaker: 6.36
  Test::More: 0.88
configure_requires:
  ExtUtils::MakeMaker: 6.36
distribution_type: module
dynamic_config: 1
generated_by: 'Module::Install version 1.06'
license: perl
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: 1.4
module_name: Mock::Apache
name: Mock-Apache
no_index:
  directory:
    - inc
    - t
    - xt
requires:
  Apache::ConfigParser: 0
  Apache::FakeTable: 0
  Capture::Tiny: 0
  Carp: 0
  Class::Accessor: 0
  Cwd: 0
  HTTP::Headers: 0
  HTTP::Response: 0
  IO::Scalar: 0
  Log::Log4perl: 0
  Module::Loaded: 0
  Readonly: 0
  Scalar::Util: 0
  URI: 0
  URI::QueryParam: 0
  parent: 0
resources:
  license: http://dev.perl.org/licenses/
  repository: https://github.com/fordmason/Mock-Apache.git
version: 0.07
