---
abstract: unknown
author:
  - 'Andrew Ford <ANDREWF@cpan.org>'
build_requires:
  ExtUtils::MakeMaker: 0
configure_requires:
  ExtUtils::MakeMaker: 0
dynamic_config: 1
generated_by: 'ExtUtils::MakeMaker version 6.62, CPAN::Meta::Converter version 2.132661'
license: unknown
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: 1.4
name: Mock-Apache
no_index:
  directory:
    - t
    - inc
requires:
  Apache::FakeTable: 0
  Readonly: 0
  URI: 0
  parent: 0
version: 0.01
