---
abstract: 'Mock Apache environment'
author:
  - 'Andrew Ford <andrew[at]ford-mason.co.uk>'
build_requires:
  ExtUtils::MakeMaker: 0
configure_requires:
  ExtUtils::MakeMaker: 0
dynamic_config: 1
generated_by: 'ExtUtils::MakeMaker version 6.64, CPAN::Meta::Converter version 2.132140'
license: perl
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: 1.4
name: Mock-Apache
no_index:
  package:
    - Apache
    - Apache::Connection
    - Apache::Constants
    - Apache::Log
    - Apache::Server
    - Apache::Table
    - Apache::URI
    - Apache::Util
requires:
  Apache::ConfigParser: 0
  Apache::FakeTable: 0
  Module::Loaded: 0
  Readonly: 0
  URI: 0
  parent: 0
version: 0.05
x_repository:
  type: git
  url: git://github.com/fordmason/Mock-Apache.git
  web: https://github.com/fordmason/Mock-Apache
